name: mail_cloud_good

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["mail_cloud.py"]
    types: [completed]
permissions: write-all
jobs:
  deploy:
# 基本系统配置
    runs-on: ubuntu-latest
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'   
# 安装依赖和工具
      - name: 安装Country.mmdb - ip库
        run: |        
          wget -O Country.mmdb https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb
      - name: 安装订阅转换工具-subconverter
        run: |
          wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
          tar -zxvf subconverter.tar.gz -C ./
          chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
# 执行任务  
      - name: Prepare #禁用了chrome
        run: pip install pyyaml requests geoip2 bs4
      - name: 执行任务 - 1.获取节点
        run: |
         python ./utils/mailCloud/getGoodSub/good.py
      - name: 执行任务 - 3.log
        run:
         python ./utils/subConvert/log.py 'mailCloud sub'
# 提交           
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./sub
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') mailCloud update done"
          git pull --rebase
      - uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
      - name: Pushes to proxies
        uses: rxsweet/copy_file_to_another_repo_action@main
        env:
         API_TOKEN_GITHUB: ghp_xxx
        with:
          source_file: 'sub/'
          destination_repo: 'rxsweet/proxies'
          user_email: 'actions@github.com'
          user_name: 'GitHub Actions'
          commit_message: 'mailCloud update done'
