sources:
- fetcher: url
  name: subs
  options:
    urls:
    - http://jjz.31465.cfd/api/v1/client/subscribe?token=4c55b1a88f0dd170cf89573cf9ba65be
    - https://subs.pithecia.com/api/v1/client/subscribe?token=573089f9130927f99a86801f3ba6184f
    - https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5
    - https://xboard.sswiwi.com/api/v1/client/subscribe?token=68337ef392c9feb5a8eca1e4d3398a0c
    - https://dj.taipeicity.news/api/v1/client/subscribe?token=21c3086bf3a948e2eec732f69943e64c
    - https://qq.xlm.plus/api/v1/client/subscribe?token=9e5db95336ab586ac6c4e2306c4d25a9
    - https://bpjc.lol/api/bpjclol?token=a2036c6e0380a346b698f6eeb5bc9998
    - https://a.aikllc.tech/api/v1/client/subscribe?token=80608a4701b46ac62e6f90e514832f61
    - https://www.kuaidog010.top/api/v1/client/subscribe?token=55ee4e169010e9a09247ac50659657c6
    - https://gbtgurl.me/api/v1/client/subscribe?token=bd0f388767d29819fced466ec0a19675
    - https://dl.vfkum.website/api/v1/client/subscribe?token=c62815476e9e93112a2d2ce3a6510d2d
    - https://api.xyurl.site/api/v1/client/subscribe?token=fed4ab7c582c2a41a08a858f91644430
    - https://qingyun.zybs.eu.org/api/v1/client/subscribe?token=da73839a390a46d9a67ef8b803158280
    - http://subssr.xfxvpn.me/api/v1/client/subscribe?token=7c6a904930e24155a93294c7fbbf16f3
    - http://feigou.zhunchuanpb.com/api/v1/client/subscribe?token=3dd452e7b921c8e82b5a83e75ab5f3e8
    - https://hQysRr.absslk.xyz/4cd433ae21ad8620914ea6e6a5526123
    - https://YKgofB.mcsslk.xyz/3a5ab556c362798b1c43be010eab9a58
    - https://5d9s2r.tosslk.xyz/3e38fbfdc09b4bd35a01e2c9e32f1b6e
    - https://sq9xy6.cpminig.com/api/v1/client/subscribe?token=d1716eb9aee63c013fab6aa99aae6e7c
    - https://xueyejiasu.com/api/v1/client/subscribe?token=95821404beb81f3bd06e03c18fdde6ae
    - https://needss.link/api/v1/client/subscribe?token=3db2aa653c4639cb54f404409a1130a8
    - https://dashuai.us/api/v1/client/subscribe?token=c2273e4488e9e856a11577972f6e91b8
  output: sub/sources/miningAll.yaml
