sources:
- fetcher: url
  name: subs
  options:
    urls:
    - https://tcxf.hssl8088.icu/api/v1/client/subscribe?token=0a422232b90558c94bf8b27d82e38cdf
    - https://d7b12d59-21aa-9561-087f-89c834ac7fe8.372372.xyz/api/v1/client/subscribe?token=f32350c82a01b364e0250785ad9897fd&amp;flag=meta
    - https://QOO3Dp.absslk.xyz/1e9aca900c9e32f74e9e2a9be1076c45
    - https://dj.taipeicity.news/api/v1/client/subscribe?token=75f7d6e2c9a37ae436903eeb2c6d136a
    - https://bpjc.lol/api/bpjclol?token=a2036c6e0380a346b698f6eeb5bc9998
    - https://www.kuaidog010.top/api/v1/client/subscribe?token=88afa549ed5e6709d188990a2965c8da
    - https://qq.xlm.plus/api/v1/client/subscribe?token=9e5db95336ab586ac6c4e2306c4d25a9
    - https://dl.vfkum.website/api/v1/client/subscribe?token=2f8c58eb73c3f732c58d6d88d27d2d69
    - https://BmmJZy.tosslk.xyz/8226d8c85fd21e0ada2d990a0ebb54f5
    - https://a.aikllc.tech/api/v1/client/subscribe?token=80608a4701b46ac62e6f90e514832f61
    - https://sq9xy6.cpminig.com/api/v1/client/subscribe?token=36cfdb8155170ffabaf5c57c17ca6dbc
    - https://subs.pithecia.com/api/v1/client/subscribe?token=573089f9130927f99a86801f3ba6184f
    - https://qingyun.zybs.eu.org/api/v1/client/subscribe?token=0243e406986c2021a546d544f2b565be
    - https://xueyejiasu.com/api/v1/client/subscribe?token=8647d7c721d91d7613dd7442aa466e20
    - https://dashuai.us/api/v1/client/subscribe?token=46a5e746f2c3a284df8a7a0cf99cce77
    - https://needss.link/api/v1/client/subscribe?token=ff5ead443f5889e32aa9e1153e91a8bc
    - https://TmyWSh.mcsslk.xyz/756b61390a8746df8675ee9d0527fad3
  output: sub/sources/miningAll.yaml
