name: get Airport

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["collect TG sub sources"]
    types: [completed]
#  schedule:
#   - cron: '25 5,13,23 * * *'
# 实际时间： 7:25, 13：25, 21:25
# 表达式生成  https://crontab.guru/

 
jobs:
  fetch:
# 系统设置开始
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2

    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'   
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-    
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
# 系统设置结束

# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 安装Country.mmdb - ip库
      run: |        
        wget -O Country.mmdb https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb
    - name: 安装订阅转换工具-subconverter
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
    - name: 安装测速工具-clash
      run: |
        wget -O clash-linuxamd64.gz https://github.com/Dreamacro/clash/releases/download/v1.11.8/clash-linux-amd64-v1.11.8.gz
        gunzip clash-linuxamd64.gz
        chmod +x ./clash-linuxamd64 && ./clash-linuxamd64 & 
        
    - name: 执行任务 - 1.check urllist
      run: |
        python ./utils/getAirport/miningAirportToSub/check.py
    - name: 执行任务 - 2.urllist to sub
      run:
       python ./utils/getAirport/miningAirportToSub/urllist2sub.py
    - name: 执行任务 - 3.fetchFreeAirport
      run: |
        python ./utils/getAirport/free/main.py
        python ./utils/getAirport/free/goodToClash.py
    - name: 执行任务 - 4.speedtest
      run: |
        python ./utils/getAirport/miningAirportToSub/speedtest.py
        sudo chmod 777 clash-linuxamd64 && python ./utils/clashspeedtest/main.py
    - name: 执行任务 - 5.log
      run:
       #python ./utils/getAirport/log.py
       python ./utils/subConvert/log.py 'airport'
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin main
        git add ./utils/getAirport/miningAirportToSub/
        git add ./sub/
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') get airport done"
        
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
    #     github_token: ${{ secrets.TOKEN }}
         branch: main

    - name: Pushes to proxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ghp_xxx
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'sweetrx@pm.me'
        user_name: 'rxsweet'
        commit_message: 'get airport done'
