name: mail_cloud
on:
  workflow_dispatch:
  schedule:
    #- cron: 30 4,10,15,23 * * * #北京时间：早7点，中午12点，晚6点,晚11点,
    - cron: 30 11,23 * * * #北京时间：早7点，晚7点
permissions: write-all
jobs:
  main:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #DDAL_EMAIL: ${{ secrets.DDAL_EMAIL }}
      #DDAL_PASSWORD: ${{ secrets.DDAL_PASSWORD }}
    steps:
      - name: 设置时区
        run: sudo timedatectl set-timezone 'Asia/Shanghai' 
      #- name: Run SubConverter
        #run: docker run -d --restart always -p 25500:25500 tindy2013/subconverter
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Prepare #禁用了chrome
        run: pip install requests beautifulsoup4 ruamel.yaml json5
      - name: 安装subconverter
        run: |
          sudo sh ./utils/airport/mailCloud/tools.sh
      - name: 执行任务 -1.Run get_trial.py
        run: |
          cd ./utils/airport/mailCloud/
          python get_trial.py
      - name: 执行任务 -2.copy to ./sub/
        run: |
          python ./utils/airport/mailCloud/copy_to_sub.py
          #cp ./utils/airport/mailCloud/trial ./sub/free64.txt
          #cp ./utils/airport/mailCloud/trial.yaml ./sub/free.yaml
          #cp ./utils/airport/mailCloud/trial.cache ./sub/sources/mail_cloud.txt
      - name: 执行任务 - 3.log
        run:
         python ./utils/subConvert/log.py 'mailCloud sub'  
      - name: Commit
        id: commit
        continue-on-error: true
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          git add ./sub/
          git add ./utils/airport/mailCloud/
          git commit -m "$(date '+%Y-%m-%d %H:%M:%S') mailCloud update done"
          #git commit -m "${{ github.workflow }} https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          git pull --rebase
      - uses: ad-m/github-push-action@master
        if: ${{ steps.commit.outcome == 'success' }}
      #- name: Run get_trial_update_url.py
        #run: python get_trial_update_url.py
      - name: Pushes to proxies
        uses: rxsweet/copy_file_to_another_repo_action@main
        env:
         API_TOKEN_GITHUB: ${{ secrets.ACTIONS_USE }}
        with:
          source_file: 'sub/'
          destination_repo: 'rxsweet/proxies'
          user_email: 'actions@github.com'
          user_name: 'GitHub Actions'
          commit_message: 'mailCloud update done'
