name: static Sub

# 触发条件
on:
  workflow_dispatch:

  schedule:
   - cron: '0 1,10 * * *'
  #  实际时间：9:00	18:00  早9点高峰，排队老是到10点半左右
  # 表达式生成  https://crontab.guru/

jobs:
  deploy:
# 基本系统配置
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: 加载缓存
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 安装Country.mmdb - ip库
      run: |        
        wget -O Country.mmdb https://github.com/Dreamacro/maxmind-geoip/releases/latest/download/Country.mmdb
    - name: 安装订阅转换工具-subconverter
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
    - name: 安装测速工具-clash
      run: |
        wget -O clash-linuxamd64.gz https://github.com/Dreamacro/clash/releases/download/v1.11.8/clash-linux-amd64-v1.11.8.gz
        gunzip clash-linuxamd64.gz
        chmod +x ./clash-linuxamd64 && ./clash-linuxamd64 & 
# 执行任务        
    - name: 执行任务 - 1.获取订阅节点
      run: |
        python ./utils/staticSub/fetch.py
    - name: 执行任务 - 2.测速
      run: |
       python ./utils/staticSub/speedtest.py
       sudo chmod 777 clash-linuxamd64 && python ./utils/clashspeedtest/main.py
    - name: 执行任务 - 3.log
      run: |
       python ./utils/subConvert/log.py 'static sub'
# 提交           
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./sub
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') staticsub node update"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main

    - name: Pushes to proxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ghp_xxx
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'staticsub node update'
