name: static Sub liteSpeedtest

# 触发条件
on:
  workflow_dispatch:
#  workflow_run:
#    workflows: ["static Sub"]
#    types: [completed]
#  schedule:
# 表达式生成  https://crontab.guru/ 
#    - cron: '10 0,6,12,18 * * *'

jobs:
  deploy:
# 基本系统配置
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: 加载缓存
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 安装订阅转换工具-subconverter
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &
    - name: 安装Country.mmdb - ip库 使用sub_convert.geoip_update()
      run: |
        python ./utils/subConvert/sub_convert.py
#执行任务
    - name: 1.set config  ----input&output位置
      run: |
        python ./utils/staticSub/litespeedtest.py       
    - name: 2.安装测速工具并运行liteSpeedtest --- 输出out.json & speedtest.log
      run: |
        sudo sh ./utils/litespeedtest/speedtest.sh
    - name: 3.输出并转换 --- output & base64 and clash
      run: |
        python ./utils/litespeedtest/output.py
#    - name: out.json & speedtest.log --- rm & mv
#      run: |       
#        rm ./sub/checkBakup/out.json
#        rm ./sub/checkBakup/speedtest.log
#        mv ./out.json ./sub/out.json
#        mv ./speedtest.log ./sub/speedtest.log

    - name: commit
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add ./sub
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') staticSub litespeedtest done"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        # github_token: ${{ secrets.TOKEN }}
        branch: main

    - name: Pushes to proxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ghp_xxx
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/proxies'
        user_email: 'actions@github.com'
        user_name: 'GitHub Actions'
        commit_message: 'staticSub litespeedtest done'
