name: TG sublist to Node

# 触发条件
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["collect TG sub sources"]
    types: [completed]
  # 表达式生成  https://crontab.guru/

 
jobs:
  fetch:
# 系统设置开始
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v2

    - name: 安装Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'   
    - name: 加载缓存
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-    
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
# 系统设置结束
    - name: 安装依赖
      run: |
        pip install -r ./utils/requirements.txt
    - name: 安装订阅转换工具-subconverter
      run: |
        wget -O subconverter.tar.gz https://github.com/tindy2013/subconverter/releases/latest/download/subconverter_linux64.tar.gz
        tar -zxvf subconverter.tar.gz -C ./
        chmod +x ./subconverter/subconverter && nohup ./subconverter/subconverter >./subconverter.log 2>&1 &        
    - name: 执行任务 - 1.TG sublist to Node
      run: |
        python ./utils/TGlist2Node/TGlist2Node.py
    - name: Commit
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git pull origin main
        git add ./sub
        git commit -m "🍀 $(date '+%Y-%m-%d %H:%M:%S')TG list fetch Node done ."
        
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
    #     github_token: ${{ secrets.TOKEN }}
         branch: main
         
    - name: Pushes to useProxies
      uses: rxsweet/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ghp_xx
      with:
        source_file: 'sub/'
        destination_repo: 'rxsweet/useProxies'
        user_email: 'sweetrx@pm.me'
        user_name: 'rxsweet'
        commit_message: 'TG list fetch Node'
