#想取消那个可以在单行开头'#'
V2board:
#优秀
  - https://www.dgycom.com/         #10G,1天，多线
#普通
  - https://fastestcloud.xyz/       #1G，2天，多线路
  - https://feiniaoyun.top/         #1G，1天，多线路
  - https://www.jcbb.top/           #1G，1天，多线路
  
SSpanel:
#优秀
  #bad - https://www.iacgbt.com/         #50G，1天，多线 
#普通  
  - https://maossr.top/             #1G,1天，多线路
  - https://skc.bar/                #50G 1天
#  - http://zhuzhu12.com/            #100G,7天，多线，需验证机器人
